TYPE MXA_AUTEXT_STATE :
STRUCT
		RC_RDY1			:	BOOL;
		ALARM_STOP		:	BOOL;
		USER_SAFE		:	BOOL;
		PERI_RDY		:	BOOL;
		ROB_CAL			:	BOOL;
		IO_ACTCONF		:	BOOL;
		STOPMESS		:	BOOL;
		PGNO_FBIT_REFL	:	BOOL;
		IntNotAus		:	BOOL;
		PRO_ACT			:	BOOL;
		PGNO_REQ		:	BOOL;
		APPL_RUN		:	BOOL;
		PRO_MOVE		:	BOOL;
		IN_HOME			:	BOOL;
		ON_PATH			:	BOOL;
		NEAR_POSRET		:	BOOL;
		ROB_STOPPED		:	BOOL;
		T1				:	BOOL;
		T2				:	BOOL;
		AUT				:	BOOL;
		EXT				:	BOOL;
		KCP_CONNECT		:	BOOL;
		BRAKETEST_MONTIME:	BOOL;
		BRAKETEST_REQ_INT:	BOOL;
		BRAKETEST_WORK	:	BOOL;
		BRAKES_OK		:	BOOL;
		BRAKETEST_WARN	:	BOOL;
		MASTERINGTEST_REQ_INT:	BOOL;
		MASTERINGTESTSWITCH_OK:	BOOL;
END_STRUCT;
END_TYPE
