TYPE MXA_AUTEXT_CONTROL :
STRUCT
		PGNO			:	BYTE;
		PGNO_PARITY		:	BOOL;
		PGNO_VALID		:	BOOL;
		EXT_START		:	BOOL;
		MOVE_ENABLE		:	BOOL;
		MOVE_DISABLE	:	BOOL;
		CONF_MESS		:	BOOL;
		DrivesON		:	BOOL;
		DrivesOFF		:	BOOL;
		BRAKETEST_REQ_EXT:	BOOL;
		MASTERINGTEST_REQ_EXT:	BOOL;
END_STRUCT;
END_TYPE
