
ACTION config: 
	gAcp6DCtrl.Status.Ready := FALSE;
	gameBrain.showHMIButton := FALSE;
	enableButtons := TRUE;
	
	shuttleStartupInfo[0].initXPos := 0.060;
	shuttleStartupInfo[0].initYPos := 0.060;
	shuttleStartupInfo[1].initXPos := 0.180;
	shuttleStartupInfo[1].initYPos := 0.180;
	shuttleStartupInfo[2].initXPos := 0.300;
	shuttleStartupInfo[2].initYPos := 0.060;
	shuttleStartupInfo[3].initXPos := 0.420;
	shuttleStartupInfo[3].initYPos := 0.180;
	
	shuttleStartupInfo[4].initXPos := 0.540;
	shuttleStartupInfo[4].initYPos := 0.060;
	shuttleStartupInfo[5].initXPos := 0.660;
	shuttleStartupInfo[5].initYPos := 0.180;
	shuttleStartupInfo[6].initXPos := 0.060;
	shuttleStartupInfo[6].initYPos := 0.300;
	shuttleStartupInfo[7].initXPos := 0.180;
	shuttleStartupInfo[7].initYPos := 0.420;
	
//	shuttleStartupInfo[8].initXPos := 0.300;
//	shuttleStartupInfo[8].initYPos := 0.300;
//	shuttleStartupInfo[9].initXPos := 0.420;
//	shuttleStartupInfo[9].initYPos := 0.420;

END_ACTION
