
TYPE
	MXA_JogAdvanced : 	STRUCT 
		Jog_Ad_Active : BOOL;
		Jog_Ad_State_Val : INT;
	END_STRUCT;
	AXIS_GROUP_REF : 	STRUCT 
		Initialized : BOOL;
		Online : BOOL;
		LastOrderID : DINT;
		ReadAxisGroupInit : BOOL;
		ReadDone : BOOL;
		IntErrorID : DINT;
		IntFBErrorID : DINT;
		HeartBeatTO : DINT;
		PLC_Major : DINT;
		PLC_Minor : DINT;
		DEF_VEL_CP : REAL;
		DEF_ACC_CP : REAL;
		Command : MXA_COMMAND;
		CmdState : MXA_COMMAND_STATUS;
		AutExtControl : MXA_AUTEXT_CONTROL;
		AutExtState : MXA_AUTEXT_STATE;
		KRCState : MXA_KRC_STATE;
		KRCControl : MXA_KRC_CONTROL;
		Jog_Advanced : MXA_JogAdvanced;
	END_STRUCT;
	AXIS_VEL :ARRAY[1..12]OF INT;
	BOOL_ARRAY_40 :ARRAY[1..40]OF BOOL;
	INT32_ARRAY_40 :ARRAY[1..40]OF DINT;
	MXA_CMD_DATA_RET :ARRAY[1..12]OF REAL;
	MXA_CMD_PAR_BOOL :ARRAY[1..50]OF BOOL;
	MXA_CMD_PAR_INT :ARRAY[1..50]OF DINT;
	MXA_CMD_PAR_REAL :ARRAY[1..100]OF REAL;
	MXA_CMD_SR_ARR :ARRAY[1..10]OF MXA_CMD_STATE_RET;
	MXA_IR_STATE :ARRAY[1..8]OF INT;
	MXA_SYNC_IO :ARRAY[1..2032]OF BOOL;
	POSITION_ARRAY :ARRAY[1..100]OF POSITION;
	REAL_ARRAY_40 :ARRAY[1..40]OF REAL;
	REAL_ARRAY_12 :ARRAY[1..12]OF REAL;
	AXIS_GROUP_REF_ARR :ARRAY[1..5]OF AXIS_GROUP_REF;
END_TYPE
