/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20221014134614_
#define _LIBRARIES_20221014134614_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CoTrace/CoTrace.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CoTrace/CoTrace.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CoTrace/CoTrace.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsZip/AsZip.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsZip/AsZip.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsZip/AsZip.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/KUKAmxA3_0.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/APO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/COORDSYS.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/E6AXIS.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/E6POS.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/FRAME.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/MXA_AUTEXT_CONTROL.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/MXA_AUTEXT_STATE.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/MXA_CMD_STATE_RET.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/MXA_COMMAND.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/MXA_COMMAND_STATUS.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/MXA_KRC_CONTROL.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/MXA_KRC_STATE.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/PNetWriteData.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/POSITION.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/AXBOX.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KUKAmxA3_0/BOX.typ\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii \"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADRINST\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RealTan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAtan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAsin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAcos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLog\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExpt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAbs\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealCos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSqrt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC3\\\" FUB\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfoDT\\\" FUB\\n\"");
#endif
#ifdef _ASIECCON_EXPORT
	__asm__(".ascii \"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_STRING\\\" FUN\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii \"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _ASSTRING_EXPORT
	__asm__(".ascii \"plcexport \\\"ftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"itoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcmp\\\" FUN\\n\"");
#endif
#ifdef _ASUDP_EXPORT
	__asm__(".ascii \"plcexport \\\"UdpOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpConnect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpDisconnect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpSend\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpRecv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpIoctl\\\" FUB\\n\"");
#endif
#ifdef _ASBRSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brsftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatod\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsitoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcmp\\\" FUN\\n\"");
#endif
#ifdef _COTRACE_EXPORT
	__asm__(".ascii \"plcexport \\\"CoTraceConfigCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceConfigLoad\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceConfigSetTiming\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceConfigOptionalParameter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceConfigAddDataPoint\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceConfigAddStartTrigger\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceRecorder\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceDataReadRecords\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CoTraceDataSaveCsv\\\" FUB\\n\"");
#endif
#ifdef _ASZIP_EXPORT
	__asm__(".ascii \"plcexport \\\"zipArchive\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"zipExtract\\\" FUB\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii \"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeLabel\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeSerialNo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _KUKAMXA3_0_EXPORT
	__asm__(".ascii \"plcexport \\\"KRC_Abort\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ActivateConvInterrupt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ActivateInterrupt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_AutomaticExternal\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_AutoStart\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_BrakeTest\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Continue\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ConvFollow\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ConvIniOff\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ConvOn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ConvSkip\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_DeactivateConvInterrupt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_DeactivateInterrupt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_DeclareInterrupt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Diag\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Error\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Forward\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_GetAdvance\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Initialize\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Interrupt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Inverse\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Jog\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_JogLinearRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_JogToolRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MasRef\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MessageReset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Move\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MoveAxisAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MoveCircAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MoveCircRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MoveDirectAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MoveDirectRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MoveLinearAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_MoveLinearRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadActualAcceleration\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadActualAxisPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadActualAxisVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadActualPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadActualVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadAnalogInput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadAnalogOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadAxisGroup\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadAxWorkspace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadBaseData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadDigitalInput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadDigitalInput1To8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadDigitalInputArray\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadInterruptState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadKRCError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadLoadData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadMXAError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadMXAStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadSafeOPStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadSoftEnd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadSoftEndExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadSysVar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadToolData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadTouchUPState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadWorkspace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_ReadWorkstates\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_SetAdvance\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_SetCoordSys\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_SetDistanceTrigger\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_SetOverride\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_SetPathTrigger\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_TechFunction\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_Test_TechFunction\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_TouchUP\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_VectorMoveOff\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_VectorMoveOn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WaitForInput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteAnalogOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteAxisGroup\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteAxWorkspace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteBaseData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteDigitalOutput1To8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteLoadData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteSoftEnd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteSoftEndExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteSysVar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteToolData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KRC_WriteWorkspace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mc_ExecuteCommand\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Move\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveAxisAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveCircularAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveCircularRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveDirectAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveDirectRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveLinearAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveLinearRelative\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_ExecuteCommand\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_GetIO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_GetIO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_GetIO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_GetIO_NIBBLE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_GetIO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_GetIO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_GetOrderState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_ResetCommand\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxa_ValuesToAPO\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxa_ValuesToCOORDSYS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_ValuesToE6AXIS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_ValuesToE6POS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_ValuesToFRAME\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_WriteIO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_WriteIO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_WriteIO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_WriteIO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mxA_WriteIO_WORD\\\" FUN\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20221014134614_ */

